services:
  db:
    image: postgres
    container_name: ax-market-database
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_HOST}
      - POSTGRES_USER=${DB_HOST}
      - POSTGRES_PASSWORD=${DB_HOST}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - application
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 15s
  app:
    build: .
    container_name: ax-market-backend
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=

networks:
  application:

volumes:
  postgres-db: